/**
 * Canonical IRI stems keyed by CURIE prefix, vendored from Bioregistry
 * (`rdf_uri_format`). Used to canonicalize a network's @context prefixes.
 *
 * AUTO-GENERATED by scripts/refresh-bioregistry.js — do not edit by hand.
 * Regenerate with: npm run refresh:bioregistry
 * Fetched: 2026-06-09
 *
 * A build-time snapshot keeps conversion deterministic and offline. A future
 * general cx2->RDF tool may resolve unknown prefixes against the live Bioregistry
 * API during conversion (with caching); see CX2_TO_RDF_DESIGN.md.
 */
export const BIOREGISTRY_PREFIXES: Record<string, string> = {
  "uniprot": "http://purl.uniprot.org/uniprot/",
  "chebi": "http://purl.obolibrary.org/obo/CHEBI_"
};
