/**
 * Chemical identifier normalization map, keyed by the CX2 `represents` value of a
 * `type: "smallmolecule"` node.
 *
 * AUTO-GENERATED by scripts/normalize-chemicals.js — do not edit by hand.
 * Regenerate with: npm run normalize:chemicals
 * Fetched: 2026-08-11
 *
 * Source: RENCI Node Normalizer, plus curated overrides recorded in that script.
 * Policy: PubChem CID (OKN-preferred) > ChEBI > unchanged source identifier.
 * Identifiers with no better target are intentionally ABSENT from this map; the
 * converter falls back to the source identifier for them.
 *
 * `exactMatch` holds only this entity's ChEBI/PubChem counterpart — deliberately
 * NOT the whole normalizer clique, which contains identifier spaces with no
 * canonical RDF IRI and, under drug_chemical_conflate, salt and formulation forms
 * that are not exact matches at all. The converter additionally emits the node's
 * original `represents` identifier, which it resolves through the network's own
 * @context.
 */
export interface ChemicalNormalization {
  /** Canonical subject IRI to use for this entity. */
  iri: string;
  /** Normalizer's preferred label, when it supplied one. */
  label?: string;
  /** ChEBI/PubChem counterpart as full IRIs, for skos:exactMatch. */
  exactMatch: string[];
}

export const CHEMICAL_NORMALIZATION: Record<string, ChemicalNormalization> = {
  "CHEBI:17336": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID445354",
    "label": "Vitamin A",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_12777"
    ]
  },
  "CHEBI:31690": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5291",
    "label": "Imatinib",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_45783"
    ]
  },
  "CHEBI:16066": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_16066",
    "label": "RETINAL",
    "exactMatch": []
  },
  "CHEBI:17898": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_17898",
    "label": "RETINAL",
    "exactMatch": []
  },
  "CHEBI:28940": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_28940",
    "label": "Ergocalciferol",
    "exactMatch": []
  },
  "CHEBI:16618": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_16618",
    "label": "1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate",
    "exactMatch": []
  },
  "CHEBI:3098": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_3098",
    "label": "bile acid",
    "exactMatch": []
  },
  "CHEBI:50114": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_50114",
    "label": "estrogen",
    "exactMatch": []
  },
  "CHEBI:24547": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_24547",
    "label": "hexadecenal",
    "exactMatch": []
  },
  "CHEBI:39026": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_39026",
    "label": "low-density lipoprotein",
    "exactMatch": []
  },
  "CHEBI:16337": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_16337",
    "label": "Phosphatidate",
    "exactMatch": []
  },
  "CHEBI:26523": {
    "iri": "http://purl.obolibrary.org/obo/CHEBI_26523",
    "label": "reactive oxygen species",
    "exactMatch": []
  },
  "CHEBI:16302": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5280382",
    "label": "11-cis-retinol",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16302"
    ]
  },
  "CHEBI:16330": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID10635",
    "label": "Stanolone",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16330"
    ]
  },
  "CHEBI:16595": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID439456",
    "label": "INS(1,4,5)P3",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16595"
    ]
  },
  "CHEBI:52392": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5282280",
    "label": "2-arachidonoylglycerol",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_52392"
    ]
  },
  "CHEBI:17489": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID6076",
    "label": "Cyclic AMP",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_17489"
    ]
  },
  "CHEBI:16356": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID135398570",
    "label": "Cyclic GMP",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16356"
    ]
  },
  "cas:11128-99-7": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID25476",
    "label": "Angiotensina II",
    "exactMatch": []
  },
  "CHEBI:48080": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5287620",
    "label": "Brefeldin A",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_48080"
    ]
  },
  "CHEBI:16113": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5997",
    "label": "Cholesterol",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16113"
    ]
  },
  "CHEBI:15354": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID305",
    "label": "Choline",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_15354"
    ]
  },
  "CHEBI:17650": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5754",
    "label": "Hydrocortisone",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_17650"
    ]
  },
  "CHEBI:4031": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5284373",
    "label": "Cyclosporine",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_4031"
    ]
  },
  "cas:51-61-6": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID681",
    "label": "Dopamine",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_18243"
    ]
  },
  "cas:50-28-2": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5757",
    "label": "Estradiol",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16469"
    ]
  },
  "cas:85305-87-9": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID6475228",
    "label": "beta-D-glucosyl-N-(tetracosanoyl)sphingosine",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_84744"
    ]
  },
  "cas:17-18-8": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID124886",
    "label": "Glutathione",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16856"
    ]
  },
  "CHEBI:28087": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID439177",
    "label": "glycogen",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_28087"
    ]
  },
  "cas:9005-49-6": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID22833565",
    "label": "Heparin",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_28304"
    ]
  },
  "cas:74-79-3": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID6322",
    "label": "Arginine",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16467"
    ]
  },
  "cas:372-75-8": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID9750",
    "label": "Citrulline",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_16349"
    ]
  },
  "CHEBI:78331": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID4878",
    "label": "PP2",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_78331"
    ]
  },
  "CHEBI:15552": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5282411",
    "label": "Epoprostenol",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_15552"
    ]
  },
  "CHEBI:37550": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5283560",
    "label": "sphingosine 1-phosphate",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_37550"
    ]
  },
  "CHEBI:61049": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID445643",
    "label": "Tacrolimus",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_61049"
    ]
  },
  "CHEBI:17347": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID6013",
    "label": "Testosterone",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_17347"
    ]
  },
  "CHEBI:15627": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID5280497",
    "label": "thromboxane A2",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_15627"
    ]
  },
  "cas:133-89-1": {
    "iri": "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID8629",
    "label": "UDP-glucose",
    "exactMatch": [
      "http://purl.obolibrary.org/obo/CHEBI_46229"
    ]
  }
};
